name: kellerkorpTestSite
favicon: null
layout_spectrum: 0.3099617715924978
typography_spectrum: 0.9621827669907361
title: Thoughts From B4
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8c96a0'
    - '#61717e'
    - '#131313'
    - '#b8b9bb'
  brandStrength: 0.8820909520145506
  lightness: 0.5175416225101799
  saturation: 0.11455010436475277
  rhythmicContrast: 0.2749662019778043
purpose: []
